apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
bases:
- ../../base

resources:
- server/server-configmap.yaml
- sealed-secrets/sealed-secret.yaml
# - server/server-secret.yaml
# - web/web-configmap.yaml

patches:
- path: replicas/db.yaml
- path: replicas/proxy.yaml
- path: replicas/server.yaml
- path: nginx.conf.yaml

configurations:
- configurations/seal-secret-config.yaml

generatorOptions:
  disableNameSuffixHash: true
  # annotations:
  #   sealedsecrets.bitnami.com/managed: "true"
  #   sealedsecrets.bitnami.com/namespace-wide: "true"

secretGenerator:
- name: server-secret
  type: Opaque
  # envs:
  # - .env.secret
