apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    role: frontend
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
      app: web
  template:
    metadata:
      labels:
        role: frontend
        app: web
    spec:
      containers:
      - name: web
        image: ghcr.io/kofeebrian/short-url-frontend:main
        imagePullPolicy: Never
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
