apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    role: frontend
    app: web
spec:
  type: ClusterIP
  selector:
    role: frontend
    app: web
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

