apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      role: backend
      app: server
  template:
    metadata:
      labels:
        role: backend
        app: server
    spec:
      containers:
      - name: server
        image: ghcr.io/kofeebrian/short-url-backend:main
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: MONGO_URI
        - name: SERVER_NAME
          valueFrom:
            configMapKeyRef:
              name: server-configmap
              key: SERVER_NAME
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: server-secret
              key: SECRET_KEY
        ports:
        - containerPort: 8080
