apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: server-secret
  namespace: dev
spec:
  encryptedData:
    SECRET_KEY: AgBM445h0lgeRf/hSf4v5MIR/i59ex+ysJ/IOf9fkVtzL50XCKw388/oui9fbFYoKK9OPdeBVbQkCCE8qHMSZvDLcqFFH/krDoUAtZK/Pbx9LjHPNb1NkpnsTGVrUxLV/GnH9dPlfNxJG67Nd/dVvz55hJ38A0nhvSZri1MzRdoKCDgY6e4ltiXS5N/T3EHi0qaF65kllXmzYtl4Y6xBa0WXnFY/Yp3126N3p2JpNpAqgBRZ1JVXfLocefKFXOumkzngpRezDbcQX8uNj8x6OR0VH03K4YqlxR7ZilfHdoA7RgJzVQGH7WTbj/rQswi18BKf90YsxQfffxZ/ypuWj+pyu2YK39rI/wUxPdLYJzcFBMP0/ZT7Iku7KHV8Zv+NLlS7Lg9eI8KcQtPjI4BsZljzKrxrQJyiy1BKwCTAPF7AjORS2Ebb0ZObJR2U6sY8OyuXp1cW88qyUSC3HM2+Of02xNKWgf9U14IPjkgi4LSuDJXbBGXBGb4wIGFV3AigTb4E43bCQh9V4qUgqYEBDE17zD0u/uR6RDe/vEiT1vTpBzv4HEPmGzmjTWZg2kRwfR4mEAoMw8wTIRhL0fzEkli/izM0XRuxuJdC+sEneRb8kbB/gj7jgWEptGFi/SNY7lHYWlGnw9yWp+7Ib0lKfuYZLqc8rE8KlWxJ9XyylF/70hXAeUq+rE7yeyqconCTfwJ4lf4ehSS6PyiEufsL5JZUwWUYSnkHrg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: server-secret
      namespace: dev
    type: Opaque

