apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: server-secret
  namespace: dev
spec:
  encryptedData:
    SECRET_KEY: AgC+ntMiGo6N5Fwbs09gpwA3hcpn7ZqhPMY+93lkJEiSjHJM352XPnvDYbHNks0QqTzfm7TgmMJUzfvnfc/2AVpPROyDv2Vxj0+v8fSyM+/ExOJlznb3XpsMM8ZrVybRbboWYuSVe3oDVZfwaEjjFAY/Nv2obLcBcUGJbh6vVqkZf5o2H03P/Udjo9E6g3NHvdYOCs3uL02K96y2UzdtQR3KtEfnU6YQzYIXiRodpZTxUccPjDikfwAV7ew+QH7HgPgbDZ8QgncIUP4aXyJyD5qVZDVzpIkbauG35O9heu3TSBPsSHy5p7AIE/zdr/HNyUSKhfBkgLRmeILD9UyxlAIYaChr8VuY26LhdbvndJyoJOjz1Vbn+BsvSjLwxjDDBaafqyLFVv9c39bIjt/z2XgHumDB1Oq3v1lD87O1r3qSgCek05yDmrHkQxpm2E1ZYNEybfiokjvzdY3jvzOH7Xku0V7bN4TUoichC+VKamcQKyxVruUVSQN5Xa2sxQ2rj7AoeZrWMRCQ6xosMtcrET7rITPbCxOniXqs5+B2B1V1sCeADMCyudax0KVCMWhyF6BQ+7e3biBOZeCeL3xOrQFCsOGLoXJPpNxpOWCODrXrsS67Gz1LYF9YQ7Q0dkWZO53YigrXgELTJ47Vcek2vCJ8Fyrv16tljjs8ce5x321qIJbE0tr/LPSuo6qjfn2w/VtEnoaURwnrJ2IzMREdgTGExUV8F1Yghg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: server-secret
      namespace: dev
    type: Opaque

